### ISSUE TITLE
add lat/lon to event template

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#102]
We use the data gathered in the events to populate maps. 

lat/lon is a required field.

**Comment by dalekunce** [comment]
@DylanMoriarty can we have gulp keep the events.csv up to date on page build as well

**Comment by smit1678** [comment]
@dalekunce Changed in https://github.com/MissingMaps/missingmaps.github.io/pull/105. Now keeps using events.csv as the way to manage events. Now located in `app/_data` folder.
