### ISSUE TITLE
discrepancy between graph and numbers?

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#104]
why are the two numbers for buildings different?
![screen shot 2016-02-25 at 7 02 34 pm](https://cloud.githubusercontent.com/assets/4806884/13338885/73676d48-dbf2-11e5-8ce8-64bf91783dfe.png)

**Comment by DylanMoriarty** [comment]
Example here: http://www.missingmaps.org/users/#/3617447

There are two different values logged for buildings created and buildings modified. It looks like the value for Buildings was only set to count the former.
