### ISSUE TITLE
Add OpenStreetMap to the credited organisations

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#106]
Where we're listing organisations at the bottom of the main page, and on the about page,  I think we should probably mention OpenStreetMap again (and put the icon). Just as a clear thank you / credit. I think it sort of goes without saying really, which is why we've forgotten to say it.

**Comment by pedrito1414** [comment]
+1

**Comment by pedrito1414** [comment]
Couple of OSM people pointing this out as well. I think they are right....
