### ISSUE TITLE
stats don't seem to match across sections or history from user profile

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#112]
why do i have 30 missingmaps changesets in projects contributed to but only 10 noted in the by the numbers section?

![screen shot 2016-02-26 at 8 17 07 pm](https://cloud.githubusercontent.com/assets/4806884/13369694/f121b076-dcc5-11e5-9b45-9eaa2e673383.png)

also, the timeline is showing edits going back to Feb 21. in my OSM history I have 16 changesets since then, which matches neither of the two above. how does it filter (hashtag and/or tasking manager bounding box?)

if there's no space between hashtags does it confuse the parsing? for example..

> # hotosm-project-1543#MissingMaps #maptime #ramanihuria

**Comment by kamicut** [comment]
Hey Dan, I'll look into your profile to understand the discrepancies better. What's your profile name?

**Comment by danbjoseph** [comment]
danbjoseph

**Comment by danbjoseph** [comment]
latest edit box shows 196 edits, the timeline only shows 73 for the same day

![screen shot 2016-04-15 at 12 36 48 pm](https://cloud.githubusercontent.com/assets/4806884/14568454/01994bc8-0307-11e6-932b-f3a26848626d.png)

**Comment by kamicut** [comment]
Can we close this @danbjoseph @dalekunce ?

**Comment by danbjoseph** [comment]
this was based on the old versions of everything
