### ISSUE TITLE
Doesn't display properly on IE 11

### ISSUE THREAD

**Issue by vdeparday** [MissingMaps/missingmaps.github.io#116]
See below: 
![image](https://cloud.githubusercontent.com/assets/1036189/13370817/13a6462c-dce2-11e5-9c20-24acca47d998.png)
![image](https://cloud.githubusercontent.com/assets/1036189/13370820/268a6386-dce2-11e5-8d76-0934b9a21920.png)

**Comment by dalekunce** [comment]
Looks like ie11 doesn't like the svg.

cc @DylanMoriarty

**Comment by dalekunce** [comment]
I tested the site on Edge and it seemed to work just fine.

**Comment by pedrito1414** [comment]
Just had an email from IE 11 user saying not working for them either. Checked analytics and over the last year ~ 10% of our visitors come through IE.

**Comment by DylanMoriarty** [comment]
Seems like IE doesn't like inline styling. Looks like this gets fixed by targeting the images in the css for width rather than in the HTML.

**Comment by dalekunce** [comment]
@DylanMoriarty are you going to submit a pull request for this.

**Comment by DylanMoriarty** [comment]
@dalekunce can do a hotfix for it. Some of this will likely get over-written by the localization branch work.
