### ISSUE TITLE
stats lag time?

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#117]
How long should it take for edits to show up in the stats? I submitted a changeset with comment: `Nepal Recovery #MissingMaps #MapGive #RedCross #hotosm-project-1540` ~36 minutes ago and the leaderboard for `hotosm-project-1540` still shows "last commit: 5 hours ago" and my user profile still shows no edits for today.

**Comment by dalekunce** [comment]
Overpass seems to be lag sometimes. replication time isn't consistent. We should maybe look at a non Overpass option. 

cc @kamicut

**Comment by kamicut** [comment]
@dalekunce @danbjoseph right, this system depends on overpass Augmented Diffs and replication metadata being in sync. This isn't always the case, causing lag/inconsistencies.
