### ISSUE TITLE
font display glitch?

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#12]
Why is the "G" not displaying correctly?
![screen shot 2015-02-11 at 5 19 02 pm](https://cloud.githubusercontent.com/assets/4806884/6144416/4a79df48-b212-11e4-846f-511fbe902b91.png)

**Comment by dalekunce** [comment]
wierd.

**Comment by danbjoseph** [comment]
killing the font-weight appears to resolve the display issue.

![screen shot 2015-02-12 at 6 03 26 am](https://cloud.githubusercontent.com/assets/4806884/6157516/f98ebce6-b27c-11e4-9065-8c5769ae008b.png)
![screen shot 2015-02-12 at 6 03 31 am](https://cloud.githubusercontent.com/assets/4806884/6157518/fc9b6df8-b27c-11e4-9666-5d257a7aa45a.png)

**Comment by danbjoseph** [comment]
css edit in 3dc6f506c20d4c207358491903bd95f44f800873
