### ISSUE TITLE
earned badges and badge progress out of sync

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#123]
http://www.missingmaps.org/users/#/1535212/badges

In Badge Progress it shows 
>Consistency
0% of the way to Level 2. Map 15 more consecutive days.

But in Earned Badges there is no Consistency - Level 1 badge.

**Comment by dalekunce** [comment]
@kamicut @DylanMoriarty 

cc @smit1678

**Comment by danbjoseph** [comment]
same issue as above but also with
> Mapathoner
33% of the way to Level 2. Participate in 10 more mapthons.

and this [profile](http://www.missingmaps.org/users/#/1815735/badges) w/ level 1 not showing in earned badges, but in progress:
> Mapathoner
13% of the way to Level 2. Participate in 13 more mapthons.

**Comment by aawiseman** [comment]
Same here, I filed a new one before seeing this: https://github.com/MissingMaps/missingmaps.github.io/issues/179

**Comment by DylanMoriarty** [comment]
Mapathoner & Consistency badges fixed.
