### ISSUE TITLE
missing changesets

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#124]
When validating I noticed a user had left traced buildings tagged area=yes. I'm messaging them with feedback and wanted to include a link to their MM profile page. But they are not showing up in the search. The edits were yesterday. See the user's [OSM profile](https://www.openstreetmap.org/user/Sara%20Mangialardo/history#map=16/28.0174/85.1389). Pascal Neis has [data on the user](http://hdyc.neis-one.org/?Sara%20Mangialardo). This is possibly related to the lag time question of #117.

![screen shot 2016-03-01 at 2 26 05 pm](https://cloud.githubusercontent.com/assets/4806884/13439024/a2bde5fc-dfb9-11e5-90c3-1e4a3a781dda.png)

![screen shot 2016-03-01 at 2 27 01 pm](https://cloud.githubusercontent.com/assets/4806884/13439043/b7c138be-dfb9-11e5-9ead-09f07da85db0.png)

**Comment by kamicut** [comment]
@danbjoseph we're only processing changesets that contain the following data:
- nodes have that the amenity tag
- ways that are either highways, waterways or buildings

What should the behavior be for contributions that are not covered by the metrics on the user pages?

**Comment by danbjoseph** [comment]
with this current configuration, a skilled mapper who spends time validating and mostly only touching features (squaring buildings, better-aligning, etc) and not creating features, will not accumulate many stats on their page? though i guess our primary audience is newer mappers.

**Comment by DylanMoriarty** [comment]
@danbjoseph we are tracking modifications to buildings & roads. Those values are added into the stats for total edits and appropriate sub categories, so if someone is just modifying buildings, that should get reflected on their page.

You can poke around in exactly what data is sent to the user by checking out the api directly, http://osmstats.redcross.org/users/1833571.

**Comment by danbjoseph** [comment]
curious about this ( [Changeset XML](http://www.openstreetmap.org/api/0.6/changeset/37570991) / [osmChange XML](http://www.openstreetmap.org/api/0.6/changeset/37570991/download) ) created & closed on 2016-03-02T17:14:05Z but [profile](http://www.missingmaps.org/users/#/1535212) calendar and ["edit_times"](http://osmstats.redcross.org/users/1535212) doesn't show any edits on March 2

**Comment by dalekunce** [comment]
This seems to be an issue with Overpass. Unlikely to be resolved on the MM site without tons of work on the osm-stats and overpass APIs
