### ISSUE TITLE
Sharing badges to twitter

### ISSUE THREAD

**Issue by nerdanel** [MissingMaps/missingmaps.github.io#126]
Currently, the predefined tweet text is

> (username) earned the (badge name) on MissingMaps!

Should we change it to either #MissingMaps or @TheMissingMaps for easier tracking/interaction?

**Comment by dalekunce** [comment]
@nerdanel :+1:

**Comment by DylanMoriarty** [comment]
The message that twitter pops up with can be found in [UserSubHead.js](https://github.com/MissingMaps/users/blob/master/src/components/UserSubHead.js), lines 137 & 139. 

The second message is for the use case when a user tries to tweet a page without any badges on it.

```
    if (this.state.badgeCheck) {
      var badgeName = this.state.userBadge;
      var badgeLevel = this.state.badgeLevel;
      twittermsg = this.state.userNameCap + ' earned the ' + badgeName + ' badge (lv.' + badgeLevel + ') on MissingMaps!';
    } else {
      twittermsg = this.state.userNameCap + ' contributed to MissingMaps! Checkout their progress at ';
    }
```

**Comment by dalekunce** [comment]
finished.
