### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by abenrob** [MissingMaps/missingmaps.github.io#135]
@tsamaya @ThomasG77 There are still a few items to clean up in the localization branch, but once we are settled on the EN content, that branch is primed for FR. I have started work on it, but I'm sure either of you could do a much better job. I can comment in this thread when we are ready to proceed, so we don't waste time/efforts re-doing too much stuff.

cc @dalekunce @pedrito1414

**Comment by abenrob** [comment]
I believe @tsamaya is currently working on this?

**Comment by smehenni** [comment]
@abenrob @tsamaya / Let me know if you still need help on this. I can correct the mistakes and translate the remaining content.

**Comment by tsamaya** [comment]
Hi @smehenni,
@abenrob merge the beginning of my translation, and the last branch for it is :   https://github.com/abenrob/missingmaps.github.io/tree/localization-patch2 
I will not be able to work on it before Tuesday evening UTC time.
let us know what you can do.

**Comment by smehenni** [comment]
Could not create the pull request, but here's my edited version (there were a few mistakes) with the translation of the **About** page. I can translate the **Hosting a Mapathon** page tomorrow if you want! (_Saved the file in .txt because I can't attach a .yml_)

[fr.txt](https://github.com/MissingMaps/missingmaps.github.io/files/163349/fr.txt)

**Comment by abenrob** [comment]
Thanks Sam. I'll pull it in tonight and let you know how it goes.

**Comment by abenrob** [comment]
#143 pulls in your additions @smehenni 
Additional edits should build off the [patch2](https://github.com/abenrob/missingmaps.github.io/tree/localization-patch2) branch until this is merged.

**Comment by abenrob** [comment]
@tsamaya, @smehenni  - would be super useful to get the translation finalized, so we can publish the translation branch, and keep branches from continuing to diverge. Extra kudos if we can wrap it this weekend. The main localization branch is now current with mine, so we need these highlighted lines translated: https://github.com/MissingMaps/missingmaps.github.io/blob/localization/app/_data/fr.yml#L152-L192
Thanks in advance !!!

**Comment by smehenni** [comment]
I'll take care of it. I'll send you an update tomorrow evening, _Eastern Time_.

**Comment by smehenni** [comment]
[Here's my translation](https://github.com/smehenni/missingmaps.github.io/tree/final-fr/app/_data)
Not sure how to do a new pull request for your branch though, I'm still new to GitHub. Help would be appreciated!

**Comment by abenrob** [comment]
Awesome @smehenni !!!
PR #147
