### ISSUE TITLE
"On Point" badge criteria too high for level 1

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#146]
It says add nodes, by this I assume it means just stand alone points. I would say 500 is way to many for level one since many things listed in the description are best represented by polygons. I hardly ever map just points. I would suggest maybe 5 or 10 for level one, maybe even 1 given how rare stand alone nodes get mapped via Missing Maps type projects.

**Comment by dalekunce** [comment]
closing I like the 500 points and for our field teams this is just a day of work.
