### ISSUE TITLE
Large parts of main website not displaying in IE 11

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#149]
Lots of parts of the website do not display in IE 11. See attached image of the front page. I have not tested the rest of the pages yet.
![2016-03-22_13h39_36](https://cloud.githubusercontent.com/assets/265831/13951997/4636ceda-f034-11e5-9ccf-bbdbbf0da26a.png)

**Comment by DylanMoriarty** [comment]
I'm having trouble replicating this bug.

@bgirardot is this still an issue on your machine? If so, can you give a bit more information about what system you're on?

**Comment by dalekunce** [comment]
Looks like at least the sequence SVG is malformed in ie

<img width="918" alt="screen shot 2016-05-24 at 11 12 15 pm" src="https://cloud.githubusercontent.com/assets/1913857/15527067/1803a544-2205-11e6-98fc-85dc13013aca.png">

cc @DylanMoriarty @bgirardot

**Comment by dalekunce** [comment]
Could this fix work.

https://gist.github.com/larrybotha/7881691
