### ISSUE TITLE
delete old PR branches

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#167]
This repo has a lot of old little PR branches

I'm not github expert, but I think it's probably best to delete branches when merging a pull request each time

**Comment by danbjoseph** [comment]
I've deleted everything that had been merged in awhile ago. 
@ViolaineCartONG  & @pedrito1414 are any of your *-patch-# branches still active?

**Comment by ViolaineCartONG** [comment]
ok for me, you can delete mines...

**Comment by pedrito1414** [comment]
ditto.

On Tue, Apr 26, 2016 at 8:17 AM, ViolaineCartONG <notifications@github.com>
wrote:

> ok for me, you can delete mines...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MissingMaps/missingmaps.github.io/issues/167#issuecomment-214648775>
>



-- 
*Pete Masters*
Missing Maps Project Coordinator
+44 7921 781 518

missingmaps.org <http://www.missingmaps.org/>

*@pedrito1414* <https://twitter.com/TheMissingMaps>
*@theMissingMaps* <https://twitter.com/TheMissingMaps>
*facebook.com/MissingMapsProject*
<https://www.facebook.com/MissingMapsProject>

**Comment by danbjoseph** [comment]
thanks all. cleaner now. down to 6.
