### ISSUE TITLE
Seem to be missing a few badges that I have earned

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#179]
Hey, it looks like I should have Mapathoner (or it says I'm on my way to levels 3) but it doesn't show that I've earned it. http://www.missingmaps.org/users/#/408282/badges

**Comment by aawiseman** [comment]
This seems to be a duplicate of https://github.com/MissingMaps/missingmaps.github.io/issues/179

**Comment by DylanMoriarty** [comment]
Checked this out. 

There seems to be an issue in the api with the Mapathoner badge not being assigned to the users. The calculations are run separately on the front end, which is why the progress is still showing up fine. We'll work to fix this soon.

**Comment by DylanMoriarty** [comment]
[Marion Barry](http://www.missingmaps.org/users/#/408282), you should have your badges now.

Mapathon badge has been fixed on the front end.
