### ISSUE TITLE
Events not showing in firefox

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#18]
Both Portsmouth and Edinburgh showing in Chrome. Nothing in forefox...

**Comment by pedrito1414** [comment]
Still not working in firefox. Do you guys need some help on this?

**Comment by dalekunce** [comment]
haven't had time to track it down. If you or a volunteer want to take a look and submit a pull request that would be great.

**Comment by danbjoseph** [comment]
I took a look at this. We just need to format the dates in the event.json file differently. All the events look like they are way past because of how it is reading them in. 

in Firefox 
```
> new Date("1/10/15")
> Date 1915-01-09T13:00:00.000Z
```
in Chrome
```
> new Date('1/10/15')
> Sat Jan 10 2015 00:00:00 GMT+1100 (VUT)
```

**Comment by pedrito1414** [comment]
So, is it just a case of editing to 2015?

**Comment by pedrito1414** [comment]
Yep, just tested. That works. Date format : mm/dd/yyyy

**Comment by dalekunce** [comment]
Need to fix all the dates in events.json to be consistent.

**Comment by pedrito1414** [comment]
Cool. I'll sort it...

**Comment by pedrito1414** [comment]
Done
