### ISSUE TITLE
BRC wishlist: Leaderboard - Export to CSV

### ISSUE THREAD

**Issue by pknight03** [MissingMaps/missingmaps.github.io#189]
Is it possible that the leader board can be exported as a csv, or a function be made available?

**Comment by dalekunce** [comment]
The leaderboards are powered by an API that is pretty powerful. Everything that you see on the site is just json restyled. For instance if you wanted to see the users for Missing Maps you can just his the following url to get JSON.

http://osmstats.redcross.org/hashtags/missingmaps/users

The entire documentation is here:
https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md

**Comment by pknight03** [comment]
Great, thanks :)
