### ISSUE TITLE
New event - Swanley, UK

### ISSUE THREAD

**Issue by Nick-Tallguy** [MissingMaps/missingmaps.github.io#19]
Hi,

I don't want to risk breaking anything - I've forked and created a branch with a commit at 

https://github.com/Nick-Tallguy/missingmaps.github.io/commit/b17a6c55786c350405cb46b33cf32d304c95e647

Can you check thoroughly and then add event please. Bit close for the first one tomorrow (it got overlooked on the wiki I think), and you may wish to change the date to the 16th, 23rd or 30th - same event details otherwise.

**Comment by dalekunce** [comment]
Nick this looks good. Can you submit it as a pull request to the main repo for historical sake.

**Comment by danbjoseph** [comment]
hey @Nick-Tallguy sorry if no one worked with you on this. the event on march 9 is included in the historical records. did the event repeat multiple times?

@dalekunce going back to csv for the data storage would make it easier for people to submit events on their own and would also make it easier to do things like check for duplicates (in a spreadsheet program).

**Comment by Nick-Tallguy** [comment]
@danbjoseph thanks for that. It's still repeating, but I don't think it's big enough to put on an international website. I've managed to build it up to 8 people that I am training, and we meet twice a week most weeks, (BST times) Thursdays 1900-2100hrs & Mondays 1300hr - 1700hrs  currently at my house. It's rare to get more than 4 at a session, but a couple of them also map in their own time - all of the recent activity on http://tasks.hotosm.org/project/955 is my group.

Running this group is one of the things that are currently taking all of my time! Be nice when I get the chance to catch up a bit.

**Comment by danbjoseph** [comment]
that's great! what a cool initiative on your part. there should be a blog post or writeup or something about it. at the least, if you have any good lessons learned etc. please send them our way so we can incorporate into training/organization materials.

**Comment by dalekunce** [comment]
Marking this as closed. @Nick-Tallguy keep up the good work.
