### ISSUE TITLE
BRC wishlist: Leaderboard - Ability to filter by date

### ISSUE THREAD

**Issue by pknight03** [MissingMaps/missingmaps.github.io#190]
At the moment cumulative figures are only displayed. Could it be possible that a time range be integrated so that a user can see their edits between two dates?

**Comment by dalekunce** [comment]
This is a great idea and something that the API could potentially support.

**Comment by aawiseman** [comment]
Yes, definitely would like this too! We have some groups that map every week so it would be great to see how much they've been doing.

**Comment by mojodna** [comment]
The API now supports date ranges on most endpoints (it still needs to be doc'd in https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md). To use it, add `start_date=<ISO-formatted date/time>` and/or `end_date=<ISO-formatted date/time>`.

(ISO-formatted date/times can be generated from JS using `new Date().toISOString()` and are parsed using `new Date(input)`, so partial dates and times like `2017-10-10` and `2017-10-10T04:00` (as well as dates with UTC offsets) are valid.)

**Comment by dalekunce** [comment]
@mojodna this is awesome, people been lusting after this

**Comment by dalekunce** [comment]
@mojodna I tried the following but it doesn't seem to work.

```
http://osmstats.redcross.org/stats/msft?start_date=2017-12-10
```

**Comment by dalekunce** [comment]
@pknight03 this is now working

https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md#date-range-queries
