### ISSUE TITLE
no stat updates

### ISSUE THREAD

**Issue by piaco** [MissingMaps/missingmaps.github.io#193]
no stat updates for the last three days.
consistency badge doesn't update at all.
worldknown badge totally missing for the last three weeks or so
Hope it can be fixed.     /piaco_dk

**Comment by kamicut** [comment]
@piaco we're working on certain issues that arose in the data pipeline. Hopefully after the fixes, we'll be able to go back and add badges historically. When the new code is up, we'll ping this issue. Thanks for keeping an eye out! 
cc @matthewhanson
