### ISSUE TITLE
mediakit

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#206]
We should push the missing maps media kit to the webpage. This should includes the updated logo with its multiple versions.

**Comment by dalekunce** [comment]
@DylanMoriarty can you remind me where all the logo materials are? Including the logo font?

**Comment by DylanMoriarty** [comment]
The font we used for the logo is Raleway, which you can grab a local copy of [here](https://www.fontsquirrel.com/fonts/raleway).

Logo files can be found in the [main repo here](https://github.com/MissingMaps/missingmaps.github.io/tree/publish/app/assets/graphics/meta). The text has been converted to outlines to keep the svg an image and to save us the trouble of loading the Raleway font exclusively for the logo. 

I can dig up a version of it without the text outlined if that'd help for the media kit as well.

**Comment by dalekunce** [comment]
Yes please

**Comment by DylanMoriarty** [comment]
Dropped it into the repo in a PR.

https://github.com/MissingMaps/missingmaps.github.io/pull/209

**Comment by dalekunce** [comment]
@danbjoseph can you move all the relevant logos and stuff to a mediakit repo. Might be a good activity for one of the interns.

**Comment by danbjoseph** [comment]
can you create the repo?

**Comment by dalekunce** [comment]
https://github.com/MissingMaps/mediakit
