### ISSUE TITLE
wildcard hashtags

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#217]
it would be cool if we could track all of HOT edits. This is kinda difficult at the moment because all hot task are hotosm-project-####

It would be really cool to track all edits for _hotosm_ or something.

**Comment by mojodna** [comment]
Implemented at the group summary level in https://github.com/AmericanRedCross/osm-stats-api/commit/79fcbb04e42272301136eb7522e37ff1f5522220

E.g. https://osmstats.redcross.org/group-summaries/hotosm*

**Comment by mojodna** [comment]
It doesn't make sense on the `/hashtags/<hashtag>/users` endpoint, as hashtags aren't included in the output. `group-summaries` is a good way to discover them though.
