### ISSUE TITLE
Changes to the "Contribute" page

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#224]
I would like to be able to send people a link to the "contribute" page so they can learn to map. Unfortunately the top of the page starts off with "Map Now" and "More Tutorials"

Yes, I realize there is small text that says scroll down and watch the videos, but that is very easy to overlook (people do not read, they skim/scan)

It would be ideal if the two links for "Map Now" and "More Tutorials" were _after_ the beginners section.

It makes sense to progress from Beginner to map now, and more tutorials, it does not make good sense to me put them before the beginners section (more tutorials? I have not seen any tutorials yet, what more?).

Alternatively, if there could be an anchor for "Beginners" so I could just share a link directly to that part of the page, that would be a compromise.

**Comment by dalekunce** [comment]
The relavent file is https://github.com/MissingMaps/missingmaps.github.io/blob/publish/app/_includes/contribute.html

Feel free to edit it and submit as a Pull Request to be reviewed and discussed.

**Comment by dalekunce** [comment]
I like your last solution of a Beginner Mapper anchor.
