### ISSUE TITLE
Assign people to groups manually

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#230]
I've found in mapathons people often forget to put in the correct hashtags, or make a typo, or do it at first but then when they get another square they forget, and so on. It would be great if someone (the organizer of the event, say) could assign certain user names to be counted as part of certain groups. 

I know you can add hashtags to the Task Manager itself but sometimes multiple separate teams work on the same task, for example.

**Comment by dalekunce** [comment]
We initially thought about going down this route. The overhead of maintaining a whitelist of all members of the group proved to be just to much. I know that this means that we lose some members of the groups but at this time we won't build out this feature.
