### ISSUE TITLE
Do leaderboard hashtags without space parse?

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#231]
I was looking for a hashtag on the Leaderboard page and when I typed "amm" it suggested a bunch, and it looks like some were multiple hashtags without spaces -- do those still get counted? If not can we parse them out?

![screen shot 2016-06-28 at 1 17 58 pm](https://cloud.githubusercontent.com/assets/5025092/16425503/15a957d2-3d33-11e6-8188-93647a811149.png)

**Comment by kamicut** [comment]
@aawiseman do you mean discard the stats from those changesets, or count amm#njmm#menlopark as counting for 3 hashtags: "amm", "njmm" and "menlopark" ?

**Comment by aawiseman** [comment]
@kamicut the latter, they meant to include all three but just left out the spaces

**Comment by kamicut** [comment]
It seems to me like this could be solved by documentation somewhere instead of trying to figure out the intent of the hashtag. For example, it could have been written as "#amm#hotosm-project-1789", "#amm #hotosm-project-1789", "#amm, #hotosm-project-1789" or "#amm,#hotosm-project-1789".

Maybe we should write in the missing maps tools that hashtags should be separated by spaces (and not commas, or stuck together, etc)?

**Comment by danbjoseph** [comment]
People don't follow documentation. What are the implications of just parsing each hashtag for any additional '#' characters and splitting the string immediately before any that are found?

**Comment by kamicut** [comment]
@danbjoseph I think this is a common user mistake that we can solve, however it will introduce an edge case where hashtags that have a secondary hash in them (if the user intended `#project-#3`, although probably uncommon) will be split up.

The way twitter solves this is by coloring the hashtag as you write it, or removing the color when the hashtag is invalid (contains commas, extra hash, etc). We can maybe add that to the common editing tools alongside documentation.

Another way to solve this is to move hashtags to the changeset metadata as an additional tag and add this as a feature of iD and pre-populating it in JOSM. While the osm-stats system won't be able to parse them as of yet, we can maybe start having this discussion. @smit1678 @mikelmaron

**Comment by mikelmaron** [comment]
> #project-#3

fwiw, I don't think this kind of pattern is common at all, and splitting on `#` `,` and ` ` is probably a safe bet

**Comment by dalekunce** [comment]
+1 @mikel @danbjoseph let's have it split on the #

**Comment by mikel** [comment]
@mikelmaron is not @mikel

**Comment by danbjoseph** [comment]
on a sorta related note. what happens with something like: 
```
DRC, #hotosm-project-1566, #MissingMaps, #MapSouthKivu, #CongoDRC #bing Added #settlements #majorroads
```
does a changeset with that comment get missed because it's `MissingMaps,` and not `MissingMaps`?

**Comment by kamicut** [comment]
@danbjoseph the hashtags are lowercased before matching, however currently we don't clean up the commas `,`. I'll look to trim those too.

**Comment by aawiseman** [comment]
It's in https://github.com/AmericanRedCross/osm-stats-workers/blob/develop/src/common/get_hashtags.js

**Comment by stephan-rayner** [comment]
I believe the regex you want for extracting hash tags looks like this. I have been testing it out in my regex tester.
` \#(.[a-z]+)/gmi `

It currently matches `#firstthing#secondthing` individually and `#firstthing` `#secondthing` but it also grabs 
`# firstthing` which I need to fix. I have to run and catch a ferry but I wanted to put this here. I will get back on this in a few hours (post travel) but I thought it was the right place to leave it.

**Comment by stephan-rayner** [comment]
Ok, it took me a bit to get the testing to work in a way that ... worked but here we are. I threw a PR up and have linked it below. Please feel free to have feels.

This solves the issue with hashtags that are clumped together without spaces and it also deals with special characters like `,` and so forth.

https://github.com/AmericanRedCross/osm-stats-workers/pull/31

**Comment by kamicut** [comment]
Thanks @stephan-rayner I'll look at the PR as soon as I can.

**Comment by dalekunce** [comment]
@kamicut can you merge this in please

**Comment by aawiseman** [comment]
@kamicut @dalekunce looks like this is still happening on my site, what do I need to do to fix it?

**Comment by dalekunce** [comment]
@mojodna any hope for this?

**Comment by mojodna** [comment]
https://github.com/AmericanRedCross/osm-stats-workers/pull/31 was merged (on 9/20/16) and not reverted. Additionally, the Lambda function was last deployed 4 months ago, so it follows that Lambda would have the latest...

**Comment by mojodna** [comment]
Downloading the deployment package from Lambda indicates that it's not the latest.

**Comment by mojodna** [comment]
Lambda appears to be at https://github.com/AmericanRedCross/osm-stats-workers/commit/cec5bcff388dc2bab2d0529aba6913730f91a09b

**Comment by mojodna** [comment]
Lambda is now up-to-date, but Travis isn't updating `gh-pages` with bundled zip files, probably because the encrypted environment vars have gone stale (or were tied to a different org).
