### ISSUE TITLE
Crisis mapping badge doesn't have an explanation

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#243]
It just has the image. Cool to see new badges tho!

<img width="449" alt="screen shot 2016-07-12 at 1 08 01 pm" src="https://cloud.githubusercontent.com/assets/5025092/16785496/5ffcc952-485c-11e6-8956-42b3f8fb8b06.png">

**Comment by DylanMoriarty** [comment]
Right. For the new badges, we were hoping that MissingMaps would be able to reach out to it's pool of users and get some enterprising ones to create new badge graphics for the system. To that end, we actually have a [PR](https://github.com/MissingMaps/users/pull/26) for the front-end of things where we give these badges a dummy graphic, 

<img width="354" alt="screenshot 2016-07-13 11 03 28" src="https://cloud.githubusercontent.com/assets/9341928/16808188/7735e684-48e9-11e6-9afc-5877be4ac246.png">

and a description that will point them towards instructions on how to contribute the graphics. 

The current PR has an issue with one of the dependencies that stopped us from being able to merge it in last week. Will be looking into it again shortly!

**Comment by aawiseman** [comment]
Cool! I meant the description itself though being blank, the others explain what the badge is

**Comment by DylanMoriarty** [comment]
Apologies that this took so long to actually merge in, but this has been resolved:

http://www.missingmaps.org/users/#/408282/badges
