### ISSUE TITLE
add comma thousand separator for numbers?

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#263]
on the leaderboard and 
<img width="258" alt="screen shot 2016-07-25 at 11 08 59 am" src="https://cloud.githubusercontent.com/assets/4806884/17111834/36b45a64-5258-11e6-8de4-5148a660730c.png">
on profile pages
<img width="172" alt="screen shot 2016-07-25 at 11 06 39 am" src="https://cloud.githubusercontent.com/assets/4806884/17111784/f0cc3b70-5257-11e6-91ea-39bd48db56d2.png">

**Comment by mojodna** [comment]
This was fixed by adding `toLocaleString()` to numbers.
