### ISSUE TITLE
user url

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#265]
make the user url route match the osm user id.

for instance:
http://www.missingmaps.org/users/#/1443840 --> http://www.missingmaps.org/users/#/dkunce

**Comment by DylanMoriarty** [comment]
This is functionally good to go, [the change exists in this User PR](https://github.com/MissingMaps/users/pull/32)- but before we merge that in, we should be sure to switch over all MissingMaps properties that are currently linking to the user pages via the id. 

Off the top of my head this includes:

- [ ] [Leaderboards](https://github.com/MissingMaps/leaderboards/pull/11)
- [ ] Partner Pages

@dalekunce @danbjoseph @rachblevine, It'd be awesome if you could chime in if we're missing something.

**Comment by kamicut** [comment]
This is now deployed on `/users`, `/leaderboards` and `/partners`
