### ISSUE TITLE
some events are in the wrong place

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#27]
@danbjoseph can you double check the lat/longs of the host locations in the events.json. Seems like some of them are in the wrong place. SOTMUS and Berlin especially.

**Comment by danbjoseph** [comment]
ea4769e45964308dca7980a39dcbbe1dc596abf9

- SOTMUS was in DC not NYC
- Berlin had correct coordinates just in the wrong order in the array
