### ISSUE TITLE
Only showing 7 events on the Events part

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#270]
I have a whole bunch of events listed in our events .csv, but only seven of them are appearing. Is that expected? Even after I hit "Show all". Or maybe I goofed something up in the code?

**Comment by aawiseman** [comment]
This is for a partner site, I should note.

**Comment by danbjoseph** [comment]
please log issues for partner pages on that project repo
https://github.com/MissingMaps/partners/issues

**Comment by aawiseman** [comment]
you got it

**Comment by danbjoseph** [comment]
issue logged in 'partners' repository
