### ISSUE TITLE
French and spanish blogs show english blog posts?

### ISSUE THREAD

**Issue by ViolaineCartONG** [MissingMaps/missingmaps.github.io#274]
As we don't already have posts in french or spanish on the blog, that won't happens that much,and that most of the things will be in english first, that would be cool to include them even if not translated in spanish and french. What do you think? If some passionating informations happens in the english section, i wouldn't like to miss them because of the language ...

**Comment by dalekunce** [comment]
when this becomes and issue maybe we can deal with it.
