### ISSUE TITLE
Track stats over a period of time

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#286]
It's hard to see what people using one hashtag have done over a certain time period -- would be cool if you could have some kind of custom time filter -- show me this hashtag since last Friday, or whatever. 

This would especially be useful for recurring events or groups that map frequently -- hey, we did 500 edits last week, let's do 600 this week!

**Comment by aawiseman** [comment]
This might be a duplicate of #190

**Comment by mojodna** [comment]
Let's call this a dupe.
