### ISSUE TITLE
"We need a badge graphic"

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#287]
There's a few badges which don't have a design yet. They say "We need a badge graphic"

![](http://www.missingmaps.org/users/assets/graphics/badges/10-1-graphic.svg)

**Comment by dalekunce** [comment]
@harry-wood this was done on purpose to encourage more community participation in the badge creation process. We didn't want to be the only ones prescribing badge creation. We very much want badges new badges to be created for and by the OSM community.

Blog post about badge creation process. https://www.developmentseed.org/blog/2016/06/09/mm-badges/

Badges are here: https://github.com/MissingMaps/users/tree/master/assets/graphics/badges

How to add badges:
https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/Adding_Badges.md
