### ISSUE TITLE
New event, Dar es Salaam

### ISSUE THREAD

**Issue by kateregga1** [MissingMaps/missingmaps.github.io#29]
For our mapping party for this month July, we would like to work on task #1120 - Missing Maps: Dar es Salaam (drone imagery). Would like to add this event on the missing maps website. Please advise.

Geoffrey Kateregga
Ramani Huria, Dar es Salaam

**Comment by pedrito1414** [comment]
Add it to the wiki, here and we'll pick it up from there http://wiki.openstreetmap.org/wiki/Missing_Maps_Project

Thanks a million for the support!

**Comment by kateregga1** [comment]
Hi @pedrito1414 

I have added the event to the wiki, let me know if something is not clear. 

Thanks.

**Comment by danbjoseph** [comment]
thanks. up on the website.

**Comment by kateregga1** [comment]
Would you please change the event time from 14.00 - 15.00, to 14.00 - 18.00.

Thanks.

**Comment by danbjoseph** [comment]
done.

**Comment by kateregga1** [comment]
Thanks.
