### ISSUE TITLE
Missing Edits

### ISSUE THREAD

**Issue by damianblanck** [MissingMaps/missingmaps.github.io#293]
I made edits in openstreetmap last night between 9PM Eastern time and 11:30 PM and don't see my edits reflected in your leader board. 

http://www.missingmaps.org/users/#/1655079
In the contribution timeline it shows that I made edits 819 on Thursday Nov 17 but those don't show up in the hash tags 

http://www.missingmaps.org/leaderboards/#/osmgeoday
http://www.missingmaps.org/leaderboards/#/malaria
http://www.missingmaps.org/leaderboards/#/dgmapathon

But the tags are in my changeset https://www.openstreetmap.org/api/0.6/changeset/43753765
Thanks for your help

**Comment by kamicut** [comment]
Thanks for reporting @damianblanck, we'll look into it and see if there was an issue with the pipeline.

**Comment by damianblanck** [comment]
Its happening again tonight. I have 32 changesets in the past 2 hours that are not showing up.

https://api.openstreetmap.org/api/0.6/changesets?display_name=BmoreGIS
