### ISSUE TITLE
blog listing needs clear

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#322]
i think https://www.w3schools.com/css/css_float.asp describes what needs to be implemented so that cover images with the wrong size don't mess up the page display on http://www.missingmaps.org/blog/

**Comment by DylanMoriarty** [comment]
Can you take a screenshot of how wrong sized cover images are showing up messed up? Is it just that there's some blank space on the sides of the container?

**Comment by danbjoseph** [comment]
![screen shot 2017-04-24 at 1 53 53 pm](https://cloud.githubusercontent.com/assets/4806884/25351087/7c9eaa1a-28f5-11e7-9056-e9e63ded0e1f.png)

**Comment by danbjoseph** [comment]
should be fixed with 49db3b304b557771806e5262bd15dca2c2788717
**before:**
<img width="1272" alt="screen shot 2017-07-28 at 10 33 36 am" src="https://user-images.githubusercontent.com/4806884/28722748-b5fc8a2a-7382-11e7-886f-9ea0e7287a27.png">
**now:**
<img width="1241" alt="screen shot 2017-07-28 at 10 51 14 am" src="https://user-images.githubusercontent.com/4806884/28722750-b792ea1e-7382-11e7-9494-d60749c7c955.png">
