### ISSUE TITLE
CORS errors on "Leaderboards" and "Userprofiles"

### ISSUE THREAD

**Issue by mikoMK** [MissingMaps/missingmaps.github.io#336]
User profiles and the leaderboard don't load. The console in Firefox logs the error: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://osmstats.redcross.org/..."

**Comment by danbjoseph** [comment]
an update to try and get osmstats using https went wrong. we'll hopefully have this fixed soon. thank you for your patience.

**Comment by dalekunce** [comment]
fixed :)
