### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by pknight03** [MissingMaps/missingmaps.github.io#351]
(1) From all the 'Discover' pages (leaderboards and users), the 'contribute' dropdown does not appear and clicking 'contribute' goes to a missing page.

(2) Also the link on the 'missing page', Help us map the world, goes back to the missing page

**Comment by danbjoseph** [comment]
see also #337 and #275

**Comment by danbjoseph** [comment]
this appears to have been resolved since.
