### ISSUE TITLE
Partner pages after switch to TM3

### ISSUE THREAD

**Issue by pknight03** [MissingMaps/missingmaps.github.io#356]
On the partner pages, the preview and progress bar no longer correspond to the TM, and all the squares are grayed out.

E.g.
http://www.missingmaps.org/partners/aviva/
http://www.missingmaps.org/partners/microsoft/
http://www.missingmaps.org/partners/cisco/

**Comment by danbjoseph** [comment]
the properties have changed to something like...
```
  "properties": {
    "taskId": 1776,
    "taskX": 41120,
    "taskY": 72215,
    "taskZoom": 17,
    "taskSplittable": true,
    "taskStatus": "MAPPED"
  }
```
https://github.com/MissingMaps/partners/blob/master/app/assets/scripts/main.js#L129
needs to be `taskStatus` not `state`
and the possible values seem to be
`MAPPED`, `READY`, `VALIDATED`, `INVALIDATED`,`LOCKED_FOR_MAPPING`

**Comment by danbjoseph** [comment]
percentMapped and percentValidated no longer need to be added to get the correct stat
https://github.com/MissingMaps/partners/blob/master/app/assets/scripts/main.js#L64

**Comment by danbjoseph** [comment]
https://github.com/MissingMaps/partners/pull/107
