### ISSUE TITLE
Add tools for 'Validating for Missing Maps Using JOSM

### ISSUE THREAD

**Issue by FransS1945** [MissingMaps/missingmaps.github.io#371]
1 ## Mark Seen plugin. 
insert after this paragraph 

> " starting in one corner, zoom in pretty close so you can see the details and begin to pan through your square and look for things that should be mapped according to the task instructions"_
Use the "MARKSEEN" tool 
![afbeelding](https://user-images.githubusercontent.com/31804031/35579130-38497344-05e6-11e8-8b49-32319afdf149.png)
to check which areas you have seen
[https://github.com/risicle/josm-markseen/blob/master/screen_20170828.png](url)

2 At the end of paragraph "Squaring Builidngs" (see typing error in document):
another tool to find non squared buildings is this script .
First you must activate Scripts in your plugin list
![afbeelding](https://user-images.githubusercontent.com/31804031/35579766-af89fcac-05e7-11e8-9dfa-94f1ffa40f4b.png)
after that visit github page (if you are new to github you first have to subscribe yourself.)
[https://github.com/MikeTho16/JOSM-Scripts]
look for  	SelectNonOrthogonalBuilding.js in the list and download it. save it in an easy to find map.
Open the scripting tab in JOSM and click 'run' and select the downloaded file.
after selecting this, run the script file. Now all buildings which meet the script will be highlighted red.
You might check them in your task first. then click on the Q button to square them all. Run the script again to see if there are any non squared buildings left. Check these first, because these might joint together on there nodes. Unglue these nodes and click again on the Q button 

3  somewhere, before the paragraph 'Using JOSM Search"? 
add the scripting tool to find duplicated buildings.
https://github.com/MikeTho16/JOSM-Scripts
SelectDuplicateBuildings.js

To Run:
* Install JOSM's Scripting Plugin
* Place above file in a convenient location on your system 
* Click "Scripting" (on top menu bar)
* Click "Run"
* Click "..." button and select this file.
* Click "Run"

Selects duplicate, or near duplicate, area buildings in JOSM's active data layer. A "near duplicate" is a building whose bounding box overlaps another building's bounding box by more than 50% (I couldn't get a pure area compare to work).  Only the first building encountered of an overlapping pair is selected. The selected buildings are added to the current selection.

**Comment by giblet22** [comment]
Added in this PR: https://github.com/MissingMaps/missingmaps.github.io/pull/372
