### ISSUE TITLE
Partner Page Update Request

### ISSUE THREAD

**Issue by rachblevine** [MissingMaps/missingmaps.github.io#375]
Can someone add a task-status section to the partner pages? If a page is less active, tasks might get achieved without them being finished and we/mappers might not notice it on the partner page as it currently displays.  They then get an error when they try and map.  Thanks!

**Comment by danbjoseph** [comment]
For user experience you don't want them to click through and get an error at the end of a link. Putting the word “archived” below a link button you can click that says `START MAPPING` isn’t going to help the audience for the partner pages. Sounds like what you might want is for the `START MAPPING` button to be disabled if a project isn't published (styling changes slightly and you can no longer click it) and the button text changed to either “draft project” or “archived project” to give an indication why the button link is disabled.

**Comment by rachblevine** [comment]
This is why they pay you the big bucks.  That would be ideal thanks!

**Comment by danbjoseph** [comment]
<img width="798" alt="screen shot 2018-02-17 at 7 54 20 am" src="https://user-images.githubusercontent.com/4806884/36338764-dcfda642-13b7-11e8-9d8d-b373ec4e2e95.png">
<img width="810" alt="screen shot 2018-02-17 at 7 54 05 am" src="https://user-images.githubusercontent.com/4806884/36338766-df77f8dc-13b7-11e8-8436-cd30e1826a66.png">
<img width="808" alt="screen shot 2018-02-17 at 7 53 46 am" src="https://user-images.githubusercontent.com/4806884/36338767-e0888f84-13b7-11e8-815f-4c4dc5774bb5.png">

**Comment by danbjoseph** [comment]
with MissingMaps/partners@d0f7e5da17452fde787ac31c56536658544cc676 removed the "read more" link to project if it's not published
