### ISSUE TITLE
Events section not appearing in FF

### ISSUE THREAD

**Issue by Eleonore9** [MissingMaps/missingmaps.github.io#38]
I can only see the list of events in Chrome but not Firefox. I'm using FF 41.0 for Ubuntu.

**Comment by danbjoseph** [comment]
thanks for pointing this out! we'll look into it as soon as possible.

**Comment by Eleonore9** [comment]
Np. I can actually try and look into it!

**Comment by danbjoseph** [comment]
Firefox parses a year of 15 as 1915 instead of 2015 so all the events end up outside the future and one week past date range.
Events data fixed w/ ec3ac18becefac9f0c43ed114b273c6cf7bee0d5.

**Comment by Eleonore9** [comment]
:+1: thanks
