### ISSUE TITLE
Can not find users on user search page - search entries changed to lowercase ?

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#382]
Not sure what the criteria is for a user to appear, but some users are not found that exist in OSM.

http://www.missingmaps.org/users/#/

Examples of not found osm users:

DorithEliabu
JanetChapman

A little testing shows that the url at least is forced to lowercase and osm usernames are case sensitive, that could be the issue.

**Comment by mojodna** [comment]
The front-end no longer forces usernames to lowercase.

The API no longer treats usernames as case-sensitive.
