### ISSUE TITLE
Stats page "contribution time line" count missing edits made

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#383]
Hi, this is a report for a missing maps contributor who maps every day of the year and is very in tune with their stats. They have been have some difficulty with stats for the past year and hopefully the new updates to MM stats has fixed most of their issues.

However, last week they continued to find an issue with the contribution time line, which is the metric they find most important (and one I think we do not highlight enough) It seems to be missing days they contribute. I have attached their screenshots that illustrate the issue.

![schermafbeelding 2018-03-20 om 08 37 26](https://user-images.githubusercontent.com/265831/37969982-7fe67bf8-31d2-11e8-8fc3-da2d762407cc.jpg)
![schermafbeelding 2018-03-21 om 14 54 28](https://user-images.githubusercontent.com/265831/37969983-80068ae2-31d2-11e8-8ff9-61d016ff4662.jpg)
![schermafbeelding 2018-03-26 om 13 52 02](https://user-images.githubusercontent.com/265831/37969985-803b309e-31d2-11e8-822b-fca5897eacf4.jpg)
![schermafbeelding 2018-03-26 om 13 51 30](https://user-images.githubusercontent.com/265831/37969984-80215570-31d2-11e8-8b58-f8e2ec6d1c77.jpg)
![schermafbeelding 2018-03-26 om 13 55 18](https://user-images.githubusercontent.com/265831/37969986-8060546e-31d2-11e8-8100-574764ba0d53.jpg)

**Comment by mojodna** [comment]
This is the only screenshot from the leaderboards using new data:

![](https://user-images.githubusercontent.com/265831/37969985-803b309e-31d2-11e8-822b-fca5897eacf4.jpg)

At rough glance, it seems to match HDYC.

Since this is done client-side, timezones are respected, though date calculations on the API side use UTC, so if no edits occur during a 24 hour window that aligns to a day in UTC, it won't get marked as a day.

**Comment by dalekunce** [comment]
To me this isn't actually an issue. Our stats, including the timeline are good now.

**Comment by Martinairmaps** [comment]
A few later: the timeline stats continue to be corrupt. Besides, for weeks in a row MM "edits made" are the same every day, no matter how much is being mapped!! First "10 edits made" for about 1 week, and untill now it notes "11 edits made" for more than 1 week!!
Also the last five day no mapping contribution is shown all!!!
However HDYC gives the correct contributios ALL the time (thanks Pascal Neis!).
I don't understand why these issues occur and continue. Please do something about it or advise!

Examples:
<img width="512" alt="afbeelding" src="https://user-images.githubusercontent.com/25906567/39577605-1a9425c0-4ee2-11e8-9d2a-cd4c8e804aa5.png">
<img width="512" alt="afbeelding" src="https://user-images.githubusercontent.com/25906567/39577173-d80828b0-4ee0-11e8-9f24-4acc4fec8009.png">
