### ISSUE TITLE
Leaderboard: Competitor not being added

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#392]
From an email contact, the user is adding the #thinkwhere hashtag, but when trying to add it via the mm leaderboard page, it does not add the competitor. other hashtags work fine.

The mm leaderboard does indicate that it was updated in the past 5 minutes so that does not seem to be the issue.

![image006](https://user-images.githubusercontent.com/265831/41347930-69fb7052-6f0b-11e8-8ec5-148802b8d632.jpg)

Pascal's tool does show changesets under that hashtag.

![2018-06-13_13h13_01](https://user-images.githubusercontent.com/265831/41347972-8f5c3dc2-6f0b-11e8-8f04-75c3931fd388.png)

**Comment by dalekunce** [comment]
I think the issue is that the data was just slow through the system.

http://www.missingmaps.org/leaderboards/#/thinkwhere

![screen shot 2018-06-13 at 4 32 58 pm](https://user-images.githubusercontent.com/1913857/41383813-7400a93e-6f27-11e8-9ede-75f75fdf7801.png)
