### ISSUE TITLE
Leader board name search buggy

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#393]
Hi, Jan and I were looking for users in the missingmaps team on the leader board but having trouble finding some users.

For example the user Piskvor is not found using 'piskvor' or 'Piskvor' but is found if I just use 'iskvor' see below.

We are not finding the users pschonmann and Datin which should be in the results for missingmaps team as well.

![2018-06-14_15h06_11](https://user-images.githubusercontent.com/265831/41414154-80fd7054-6fe5-11e8-9eb1-faff4eae5c8d.png)
![2018-06-14_15h06_23](https://user-images.githubusercontent.com/265831/41414158-83b314de-6fe5-11e8-8b2a-dcfda7f8b071.png)
![2018-06-14_15h06_34](https://user-images.githubusercontent.com/265831/41414160-8541d484-6fe5-11e8-9733-d7d937860875.png)

**Comment by giblet22** [comment]
This is the same for my username "Giblet" maybe something to do with the uppercase character to start?

**Comment by bgirardot** [comment]
I thought maybe that too, but pschonmann for sure is an all lowercase osm username.

https://www.openstreetmap.org/user/pschonmann

**Comment by bgirardot** [comment]
@giblet22 I am not sure now, you can go to mm team listing and try and type in any of the names that start with capital letters and they are not found in the search.

I guess this is just the same as issue #382 but I thought that was fixed. Sorry just remembered that issue existed.

**Comment by mojodna** [comment]
In order to improve performance, the leaderboards switched to using a paginated API endpoint (500 users at a time rather than the full 10k+, more as time goes on). Since search is implemented within the browser, if a user is not within the first 500 (more if you've scrolled and triggered pagination) results (according to whichever sorting criteria is active), s/he won't be found.

A potential fix to this is to create a "search within specific leaderboard" endpoint in the API which returns contextual results (+/- 50 users within the same sort order).

**Comment by bgirardot** [comment]
@mojodna I still think there is a case issue going on as you can see the listing of users and if you try to find any of them who have a capital letter as the first letter in their name, you can not find them via the search box. Just visit the leaderboard listing, pick any user with a capital letter first name and try to find them via the search box on the page. Hopefully the below gif illustrates that.

![leaderboard-search](https://user-images.githubusercontent.com/265831/41426630-8856d0e2-7004-11e8-81a9-3f55c509ab38.gif)

**Comment by mojodna** [comment]
Ah, I think I know why that might be the case; usernames were previously forced to lowercase (with unintended consequences) and there's probably something sticking around that lowercases the search query. If so, it should be a quick fix.
