### ISSUE TITLE
Guide to validation using the JOSM editor miss pictures

### ISSUE THREAD

**Issue by qeef** [MissingMaps/missingmaps.github.io#403]
On page http://www.missingmaps.org/validate/ there is "guide to validation using the JOSM editor" downloadable from www.missingmaps.org/assets/downloads/MissingMaps_validation_josm_en.pdf

In the pdf, there are no pictures, just HTML tags.

**Comment by qeef** [comment]
Cannot add `bug` label.

**Comment by danbjoseph** [comment]
seems like [`markdown-pdf`](https://www.npmjs.com/package/markdown-pdf) isn't interpreting the html within the markdown source document when creating the file
https://github.com/MissingMaps/missingmaps.github.io/blob/publish/gulpfile.js#L95
