### ISSUE TITLE
Trailing slash on url to wiki link causes wrong page to load

### ISSUE THREAD

**Issue by wireguy** [MissingMaps/missingmaps.github.io#408]
Having a trailing slask ('/') on the url to wiki.openstreetmap.org pages assumes the user wants to create a new wiki page under the intended page.

4 files impacted:
app/_data/cs.yml
app/_data/es.yml
app/_data/fr.yml
app/_data/en.yml

2 links found with trailing slash:
http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager/Validating_data/
http://wiki.openstreetmap.org/wiki/Highway_Tag_Africa/

submitted pr #407  to remove the trailing slash.

please verify.

**Comment by danbjoseph** [comment]
@wireguy fixed with #407
