### ISSUE TITLE
User badges thing not working

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#76]
Oooh new website, with new bits!

This thing http://www.missingmaps.org/users/#/  is not working though.

Type in a name and safari logs a js error:
`TypeError: undefined is not an object (evaluating 'user.id') rethrowCaughtErrorbundle.js:50119`

But maybe I just need to give you chance to get it working :-)

**Comment by smit1678** [comment]
@harry-wood Thanks for the flag, just rolled out last night. Just to confirm, you're seeing this on Safari? What version of OS X?

**Comment by harry-wood** [comment]
Mac OS X 10.9.5  I see the same thing in Chrome too. But... I think this is not a browser issue

Something different to what you're expecting. My own username has an awkward space character, but I tested a few different ones such as 'wonderchook' & 'DrishT'  but then...

with 'pedrito1414' ...success!

Do the user need to make changesets using some hashtags? (and what happens if it finds no such changesets?)

**Comment by dalekunce** [comment]
@harry-wood the user must exist. We made a decision to not back fill the database but to start and move forward. If a user isn't in the db and doesn't have a page it means they need to go map :)

**Comment by harry-wood** [comment]
Ah ok. Sorry for the vagueness. So I can be a lot more specific now: https://github.com/MissingMaps/missingmaps.github.io/issues/78
