### ISSUE TITLE
User badges system. Catch the 'no data' case

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#78]
The user badges thing: http://www.missingmaps.org/users/#/  ..should catch the 'no data' case, and say something like 

_"Sorry. No data for this user.  Since we started gathering data (Feb 2016) we haven't picked up any edits by this user. Go do some mapping, then come back and try again!"_

Currently it silently fails logging a js error `TypeError: undefined is not an object (evaluating 'user.id') rethrowCaughtErrorbundle.js:50119`

**Comment by dalekunce** [comment]
+1

**Comment by dalekunce** [comment]
@kamicut can you have an error message and with a button/link to /contribute

**Comment by DylanMoriarty** [comment]
PR open for this currently in the User pages.

**Comment by harry-wood** [comment]
That PR was merged. Was it deployed? This basic issue doesn't seem to be fixed (re-open?)

**Comment by harry-wood** [comment]
OK now I see it's fixed on the live site. (Seeing this)

![screen shot 2016-05-09 at 12 09 19](https://cloud.githubusercontent.com/assets/227525/15111468/1bab7b7c-15df-11e6-9c73-732baf64fb13.png)

Yay!

but ...it's OpenStreetMap not OpenStreetMaps
