### ISSUE TITLE
Current Leader Board - "Delete" option on cards should not show when only 1 card

### ISSUE THREAD

**Issue by bgirardot** [MissingMaps/missingmaps.github.io#80]
When there is just one leader card on the Current Leader section of the Leader board section of the site

The three dots and "delete" option should not be displayed.

**Comment by dalekunce** [comment]
suggest changing "delete" to "hide" so users don't think they are removing data from the database

**Comment by bgirardot** [comment]
i will note that in the live version (sorry was looking at staging) the 3 dots no longer appear, but the option to delete can still be clicked on even though there is no UI element visible.

**Comment by bgirardot** [comment]
actually i don't see the 3 dot ui even when there are multipe cards, but the delete option is still there if you know where the ui element should be

**Comment by smit1678** [comment]
@dalekunce @bgirardot Yeah there should be a three dot element. It seems to be working when running locally so we need to look into why it's not showing up on the deployed version.

**Comment by DylanMoriarty** [comment]
Looks like this might just be a bug with paths for the image files. Fixing.
