### ISSUE TITLE
Site look and feel: more operational?

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#83]
The new graphics are nice, but I feel the faceless people kind of dominate - I guess to emphasise community. There are not many maps and no data represented and the only bit of humanitarian work is the bit where the guy is giving the other two a bit of a cuddle. It's not very operational....

In my experience, the reason people show up to our mapathons in London is to help MSF, RC, etc.  One of the reasons they come back again and again is community, but by then they are probably not looking at the website....

I think the website could convey better the fact that volunteers are contributing directly to life-saving work in the field.

**Comment by dalekunce** [comment]
@pedrito1414 I think this can be solved through a blog that tells these stories with photos/video

**Comment by pedrito1414** [comment]
But only for those users that get that far... Just my opinion but worth doing a bit of research I think....
