### ISSUE TITLE
Becoming a member - requirements

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#85]
There is nothing to say who can become a member... For example can all of the following be a member?

- individuals
- single schools
- businesses
- NGOs

I can see us getting a lot of useless contact which will eat someone's time. Maybe we should outline who can join?

**Comment by dalekunce** [comment]
did we have content for this on the old website? Agree we should add it.

**Comment by pedrito1414** [comment]
I can put some text together...

**Comment by pedrito1414** [comment]
New subhead: Membership

Membership of the the Missing Maps Project is open to any NGO, educational establishment or civil society group willing to contribute to the goals, and abide by the ethics, stated above. Approval of membership is the responsibility of the current member organisations.

If you are interested in putting an organisation forward for membership, please contact us using the form below.
