### ISSUE TITLE
Change text in 'step 3' on How we work

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#86]
Make it more immediate and operational. Something like:

Humanitarian organisations are using the map data to respond to disease outbreaks and disasters, and to plan risk reduction which saves lives.

**Comment by DylanMoriarty** [comment]
@pedrito1414 
<img width="1018" alt="screenshot 2016-02-25 13 00 47" src="https://cloud.githubusercontent.com/assets/9341928/13328994/afef4d68-dbbf-11e5-8c13-0a4b92259393.png">

Modified the text slightly to keep it in the present tense.

**Comment by pedrito1414** [comment]
Thanks!
