### ISSUE TITLE
Change 'events' to 'mapping parties'

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#91]
It's cooler

**Comment by dalekunce** [comment]
just the page title?

**Comment by pedrito1414** [comment]
I'd say in the navigation....

**Comment by harry-wood** [comment]
"Mapping Parties" means going out mapping though ( http://wiki.openstreetmap.org/wiki/Mapping_parties )  The term "Mapathons" has been used a lot for bring-a-laptop armchair mapping get-togethers

**Comment by dalekunce** [comment]
Leaving this as events.
