### ISSUE TITLE
Link username in leaderboard to user page

### ISSUE THREAD

**Issue by leonmvd** [MissingMaps/missingmaps.github.io#92]
Now the link is directing to the search page

**Comment by DylanMoriarty** [comment]
@leonmvd are you getting this from clicking on the usernames inside the leaderboard? It seems like it's working.

**Comment by leonmvd** [comment]
Yes, maybe its a safari on mac issue?

-----Original Message-----

**Comment by DylanMoriarty** [comment]
<img width="1000" alt="screenshot 2016-02-25 15 35 06" src="https://cloud.githubusercontent.com/assets/9341928/13333503/6163700a-dbd5-11e5-942f-4572cb03a212.png">

There we go. Yeah I can replicate this now.

Strange tho- it's definitely providing the right link to the user pages.

**Comment by DylanMoriarty** [comment]
Looking into this further it seems to be an issue with React-router & Safari on the Userpages. Still looking to see which tool is the one causing the issue.
