### ISSUE TITLE
new badges

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#97]
need a readme and guidelines for creating new badges

**Comment by kamicut** [comment]
@dalekunce your closing commit for this doesn't match the issue. Is this closed?

**Comment by dalekunce** [comment]
whoops

**Comment by DylanMoriarty** [comment]
Documentation for adding new badges has been added in the OSM Stats repos. To make it that more  explicit, links to it have been added to the User Page repo's readme.
