### ISSUE TITLE
Feature: Event Map

### ISSUE THREAD

**Issue by DylanMoriarty** [MissingMaps/missingmaps.github.io#98]
One feature we discussed would be nice to have was a map next to the 'events' section of the site that is populated with points for the locations where events have taken place.

Design wise this could just be a static outline of the world with dots on it via geojsons.

**Comment by leonmvd** [comment]
My colleague Quinten made one with Cartodb, will ask him to share the stuff

**Comment by dalekunce** [comment]
@leonmvd would prefer not to add external dependencies. I think we will either add a d3 or leaflet simple version.

**Comment by danbjoseph** [comment]
basic version created with cbf6c7b1b74411f9c9959f76db19980720fa84f3
